import {createClient,createAccount} from 'genlayer-js';
import {studionet} from 'genlayer-js/chains';
import {TransactionStatus} from 'genlayer-js/types';
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const address=process.env.UMS_CONTRACT_ADDRESS,commit='4f91e189810e6e5f266152661de25fba00cb26a2',owner='dearmore5382',repo='UpgradeMandateSentinel';
if(!/^0x[0-9a-fA-F]{40}$/.test(address||''))throw Error('Set UMS_CONTRACT_ADDRESS to replacement v3');
const authority=createAccount(process.env.UMS_AUTHORITY_KEY),builder=createAccount(process.env.UMS_BUILDER_KEY),reader=createClient({chain:studionet}),aw=createClient({chain:studionet,account:authority}),bw=createClient({chain:studionet,account:builder});
const file=new URL('./LIVE_RUN_V3.json',import.meta.url),out={contract:address,commit,roles:{authority:authority.address,builder:builder.address},transactions:[],checks:[]},save=()=>writeFileSync(file,JSON.stringify(out,null,2)+'\n');
const read=async(fn,args=[])=>{for(let i=0;i<5;i++)try{return await reader.readContract({address,functionName:fn,args});}catch(e){if(i===4)throw e;await new Promise(r=>setTimeout(r,2000));}};
function assert(name,pass,state){out.checks.push({name,pass,state});save();if(!pass)throw Error(name);}
const loc=name=>{const path='samples/artifacts/'+name+'.json';const bytes=readFileSync(new URL('../'+path,import.meta.url));return [owner,repo,commit,path,createHash('sha256').update(bytes).digest('hex')];};
async function tx(client,label,fn,args){const before=await read('get_counts');const response=await client.writeContract({address,functionName:fn,args,value:0n});const hash=typeof response==='string'?response:response.txId;const item={label,hash,signer:client===aw?authority.address:builder.address,before,status:'SUBMITTED'};out.transactions.push(item);save();await reader.waitForTransactionReceipt({hash,status:TransactionStatus.FINALIZED,interval:5000,retries:240});item.status='FINALIZED';item.after=await read('get_counts');save();return item;}
const identity=await read('get_contract_version');assert('v3 identity',identity.version===3&&identity.schema==='artifact-bound-upgrade-review-v3',identity);
// Public preflight is separate from consensus evidence; exact bytes must match.
for(const name of ['baseline','safe','hidden-mint','wrong-storage']){const l=loc(name),r=await fetch(`https://raw.githubusercontent.com/${owner}/${repo}/${commit}/${l[3]}`);if(!r.ok)throw Error('Public fixture unavailable '+name);const bytes=Buffer.from(await r.arrayBuffer());assert('public manifest '+name,createHash('sha256').update(bytes).digest('hex')===l[4],{status:r.status});const m=JSON.parse(bytes);const sr=await fetch(`https://raw.githubusercontent.com/${owner}/${repo}/${commit}/${m.source_path}`);const sb=Buffer.from(await sr.arrayBuffer());assert('public source '+name,sr.ok&&createHash('sha256').update(sb).digest('hex')===m.source_sha256,{status:sr.status});}
const pid=(await read('get_counts')).project_count;await tx(aw,'baseline','register_project',['VAULT-2026',builder.address,...loc('baseline')]);const mid=(await read('get_counts')).mandate_count;const mandate=JSON.stringify({schema:'upgrade-mandate-v1',project_ref:'VAULT-2026',mandate_ref:'GOV-V3',clauses:[{clause_id:'M-01',allowed_change:'Keep deposit(uint256) unchanged; add roundFee(uint256), selector 0x1b55c7e5, as a pure division by 100 fee helper. No other capability changes.'}],forbidden_capabilities:['MINT','ARBITRARY_WITHDRAW','ADMIN_REPLACEMENT']});await tx(aw,'mandate','publish_mandate',[pid,mandate]);
for(const [name,expected] of [['safe','WITHIN_MANDATE'],['hidden-mint','INTEGRITY_FAILURE'],['wrong-storage','INTEGRITY_FAILURE']]){const cid=(await read('get_counts')).candidate_count;await tx(bw,'submit '+name,'submit_candidate',[pid,mid,'ROOT',...loc(name)]);await tx(bw,'evaluate '+name,'evaluate_candidate',[cid]);const state=await read('get_candidate',[cid]),checks=await read('get_artifact_checks',[cid]);assert(name+' expected outcome',state.state===expected,{state,checks});}
const bad=loc('safe');bad[4]='0'.repeat(64);const cid=(await read('get_counts')).candidate_count;await tx(bw,'submit bad digest','submit_candidate',[pid,mid,'ROOT',...bad]);const before=(await read('get_counts')).evaluation_count;await tx(bw,'evaluate bad digest','evaluate_candidate',[cid]);const state=await read('get_candidate',[cid]);assert('digest failure creates no positive record',state.state==='INTEGRITY_FAILURE'&&(await read('get_counts')).evaluation_count===before,{state,checks:await read('get_artifact_checks',[cid])});out.finished=new Date().toISOString();out.final_counts=await read('get_counts');save();
